openapi: "3.0.1"

info:
  title: "Product"
  version: "1"
  description: Product API

servers:
  - url: http://localhost:8081/api
    description: Local server

paths:

  /manager/product:
    post:
      summary: Save Product
      operationId: saveProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'

      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        "405":
          description: Invalid input
  /manager/productUpdate/{id}:
    put:
      summary: Update an existing product
      description: Update an existing product by Id
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          description: ID of product to update
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent product in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        "405":
          description: Invalid input

  /manager/product/{id}:
    get:
      summary: Get Product By Id
      operationId: getProductById
      parameters:
        - name: id
          in: path
          description:  Id of an Product to return
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
  /manager/productAll:
    get:
      summary: Get Products
      operationId: getProducts
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDTO'

components:
  schemas:
    Response:
      type: object
      additionalProperties:
        type: object
    ProductDTO:
      type: object
      description: Data element for User
      properties:
        idProduct:
          type: string
        description:
          type: string
        productType:
          type: string

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string